### ISSUE TITLE
Embedding error when using camemBERT instead of Roberta

### ISSUE THREAD

**Issue by nicedlp** [eladsegal/tag-based-multi-span-extraction#14]
Hi, 
I have been trying to use your code to train a multispan model on French corpus, so I used Camembert instead of Roberta. To simplify, I kept only the passage_span head and multi_span head. I tried to adapt the config file for IO_SSE scheme. Here are my config files.

[config_files.zip](https://github.com/eladsegal/tag-based-multi-span-extraction/files/8799787/config_files.zip)

I get the following error : 
```bash
Traceback (most recent call last):
  File "QA_project_multispans/run.py", line 50, in <module>
    main()
  File "QA_project_multispans/venv/lib/python3.8/site-packages/allennlp/commands/__init__.py", line 120, in main
    args.func(args)
  File "QA_project_multispans/venv/lib/python3.8/site-packages/allennlp/commands/train.py", line 142, in train_model_from_args
    train_model_from_file(
  File "QA_project_multispans/venv/lib/python3.8/site-packages/allennlp/commands/train.py", line 192, in train_model_from_file
    return train_model(
  File "QA_project_multispans/venv/lib/python3.8/site-packages/allennlp/commands/train.py", line 289, in train_model
    metrics = trainer.train()
  File "QA_project_multispans/venv/lib/python3.8/site-packages/allennlp/training/trainer.py", line 536, in train
    train_metrics = self._train_epoch(epoch)
  File "QA_project_multispans/venv/lib/python3.8/site-packages/allennlp/training/trainer.py", line 373, in _train_epoch
    loss = self.batch_loss(batch_for_step, for_training=True)
  File "QA_project_multispans/venv/lib/python3.8/site-packages/allennlp/training/trainer.py", line 286, in batch_loss
    output_dict = self.model(**batch)
  File "QA_project_multispans/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "QA_project_multispans/src/models/multi_head_model.py", line 141, in forward
    token_representations = self._transformers_model(question_passage_tokens, 
  File "QA_project_multispans/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "QA_project_multispans/venv/lib/python3.8/site-packages/transformers/modeling_bert.py", line 735, in forward
    embedding_output = self.embeddings(input_ids=input_ids, position_ids=position_ids, token_type_ids=token_type_ids, inputs_embeds=inputs_embeds)
  File "QA_project_multispans/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "QA_project_multispans/venv/lib/python3.8/site-packages/transformers/modeling_roberta.py", line 67, in forward
    return super(RobertaEmbeddings, self).forward(input_ids,
  File "QA_project_multispans/venv/lib/python3.8/site-packages/transformers/modeling_bert.py", line 188, in forward
    token_type_embeddings = self.token_type_embeddings(token_type_ids)
  File "QA_project_multispans/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "QA_project_multispans/venv/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 158, in forward
    return F.embedding(
  File "QA_project_multispans/venv/lib/python3.8/site-packages/torch/nn/functional.py", line 2183, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self

Process finished with exit code 1
```

I can see in debug mode that I end up with a _weight_ variable of shape (1,768) and an _input_ variable requesting for id 1 of _weight_, while _weight_ contains only 1 row, so maximum index = 0. I don't understand why I got there though.

I launch the program with this code: 
```python
import json
import shutil
import sys
import os
from allennlp.commands import main

config_file = "configs/drop/bert/drop_camembert_TASE_IO_SSE.jsonnet"

# Use overrides to train on CPU.
overrides = json.dumps({"trainer": {"cuda_device": -1}})

serialization_dir = "/tmp/debugger_train"
# Getting the list of directories
serialization_dir_content = os.listdir(serialization_dir)
# Checking if the list is empty or not
if len(serialization_dir_content) == 0:
    print("Empty serialization directory")
else:
    print("Serialization directory not empty. Deleting content before training ...")
    for filename in serialization_dir_content:
        file_path = os.path.join(serialization_dir, filename)
        try:
            if os.path.isfile(file_path) or os.path.islink(file_path):
                os.unlink(file_path)
            elif os.path.isdir(file_path):
                shutil.rmtree(file_path)

        except Exception as e:
            print('Failed to delete %s. Reason: %s' % (file_path, e))
    print("Deletion done")

# Assemble the command into sys.argv
sys.argv = [
    "allennlp",  # command name, not used by main
    "train",
    config_file,
    "-s", serialization_dir,
    "--include-package", "src",
    "-o", overrides,
    "--cache-directory", "pretrained_models/camembert"
]

main()

```
While I understand the general architecture described in the paper, I am still lost to make sense of this error. 

Does anyone know how to solve this ?

Regards

**Comment by eladsegal** [comment]
Hi,
I think the issue is with this part:
https://github.com/eladsegal/tag-based-multi-span-extraction/blob/428dc35788a1c4cd9f6471c52b50927ed665964c/src/models/multi_head_model.py#L138-L142

RoBERTa and CamemBERT have the same architecture which is without token type embeddings, so try to change 
```
if not self._pretrained_model.startswith('roberta-') 
```
to
```
if all(not self._pretrained_model.startswith(pretrained_model_prefix) 
  for pretrained_model_prefix in ['roberta-', 'pretrained_models/camembert'])
```

**Comment by nicedlp** [comment]
Thanks a lot for your prompt and detailed answer. That was indeed the problem.
