### ISSUE TITLE
Expecting property name enclosed in double quotes

### ISSUE THREAD

**Issue by gokul427** [eladsegal/tag-based-multi-span-extraction#19]
CMD used to predict:
allennlp predict **TASE_IO+SSE.gz** drop_data/drop_dataset_dev.json --predictor machine-comprehension --cuda-device 0 --output-file predictions.jsonl --use-dataset-reader --include-package src -o "{'validation_dataset_reader.pickle.action': 'None'}"
2022-12-29 12:27:06,707 - INFO - transformers.file_utils - PyTorch version 1.13.1 available.
2022-12-29 12:27:06,855 - INFO - pytorch_pretrained_bert.modeling - Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
2022-12-29 12:27:09,383 - INFO - allennlp.models.archival - loading archive file TASE_IO+SSE.gz
2022-12-29 12:27:09,384 - INFO - allennlp.models.archival - extracting archive file TASE_IO+SSE.gz to temp dir C:\Users\gokul\AppData\Local\Temp\tmp913hu9t_
2022-12-29 12:27:20,008 - WARNING - allennlp.common.params - error loading _jsonnet (this is expected on Windows), treating C:\Users\gokul\AppData\Local\Temp\tmp913hu9t_\config.json as plain json
2022-12-29 12:27:20,009 - WARNING - allennlp.common.params - error loading _jsonnet (this is expected on Windows), treating snippet as plain json
Traceback (most recent call last):
  File "C:\Users\gokul\anaconda3\envs\py37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\gokul\anaconda3\envs\py37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\gokul\anaconda3\envs\py37\Scripts\allennlp.exe\__main__.py", line 7, in <module>
  File "C:\Users\gokul\anaconda3\envs\py37\lib\site-packages\allennlp\run.py", line 19, in run
    main(prog="allennlp")
  File "C:\Users\gokul\anaconda3\envs\py37\lib\site-packages\allennlp\commands\__init__.py", line 120, in main
    args.func(args)
  File "C:\Users\gokul\anaconda3\envs\py37\lib\site-packages\allennlp\commands\predict.py", line 240, in _predict
    predictor = _get_predictor(args)
  File "C:\Users\gokul\anaconda3\envs\py37\lib\site-packages\allennlp\commands\predict.py", line 141, in _get_predictor
    overrides=args.overrides,
  File "C:\Users\gokul\anaconda3\envs\py37\lib\site-packages\allennlp\models\archival.py", line 227, in load_archive
    config = Params.from_file(os.path.join(serialization_dir, CONFIG_NAME), overrides)
  File "C:\Users\gokul\anaconda3\envs\py37\lib\site-packages\allennlp\common\params.py", line 526, in from_file
    overrides_dict = parse_overrides(params_overrides)
  File "C:\Users\gokul\anaconda3\envs\py37\lib\site-packages\allennlp\common\params.py", line 181, in parse_overrides
    return unflatten(json.loads(evaluate_snippet("", serialized_overrides, ext_vars=ext_vars)))
  File "C:\Users\gokul\anaconda3\envs\py37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\gokul\anaconda3\envs\py37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\gokul\anaconda3\envs\py37\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
2022-12-29 12:27:20,028 - INFO - allennlp.models.archival - removing temporary unarchived model dir at C:\Users\gokul\AppData\Local\Temp\tmp913hu9t_

ENV: py3.7
allennlp @ git+http://github.com/eladsegal/allennlp@2143c7c09b95a4a4f1fd36dc595404d483b234b6
transformers==2.3.0

**Comment by gokul427** [comment]
Finally, I solved this problem by pip install jsonnetbin
