### ISSUE TITLE
RuntimeError: RUNTIME ERROR: Must override reader.answer_generator_names_per_type

### ISSUE THREAD

**Issue by Joyce94** [eladsegal/tag-based-multi-span-extraction#5]
Hi, I am attempting to reproduce the results and hitting the error "RUNTIME ERROR: Must override reader.answer_generator_names_per_type". Traceback as follows. Any help would be appreciated.

Traceback (most recent call last):
  File "allennlp/run.py", line 23, in <module>
    run()
  File "allennlp/run.py", line 19, in run
    main(prog="allennlp")
  File "/data/songy/project_allennlp/tag-based-multi-span-extraction/allennlp/commands/__init__.py", line 120, in main
    args.func(args)
  File "/data/songy/project_allennlp/tag-based-multi-span-extraction/allennlp/commands/train.py", line 150, in train_model_from_args
    args.cache_prefix,
  File "/data/songy/project_allennlp/tag-based-multi-span-extraction/allennlp/commands/train.py", line 191, in train_model_from_file
    params = Params.from_file(parameter_filename, overrides)
  File "/data/songy/project_allennlp/tag-based-multi-span-extraction/allennlp/common/params.py", line 527, in from_file
    file_dict = json.loads(evaluate_file(params_file, ext_vars=ext_vars))
RuntimeError: RUNTIME ERROR: Must override reader.answer_generator_names_per_type
	configs/drop/abstract/../../abstract/model.jsonnet:92:44-104	object <anonymous>
	configs/drop/abstract/drop_model.jsonnet:(2:8)-(22:2)	object <anonymous>
	During manifestation

**Comment by Joyce94** [comment]
Hi, I attempt to run the command "jsonnet model.jsonnet" and hit the same error. Traceback as follows.

RUNTIME ERROR: Must override reader.answer_field_generators
	model.jsonnet:91:36-88	object <anonymous>
	model.jsonnet:(85:23)-(100:6)	object <anonymous>
	During manifestation

**Comment by eladsegal** [comment]
Hi @Joyce94,
Can you tell me what was the command you tried for training?
Only configurations which aren't under "abstract" folder can be be compiled to a JSON file.

**Comment by Joyce94** [comment]
Hi, I use the command "allennlp train configs/drop/abstract/drop_model.jsonnet -s tmp --include-package src" and meet the problem. Thanks, when I use the configurations which aren't under "abstract" folder, there is no problem now.
